Algoritmo "semnome"
// Disciplina  : LPOO
// Professor   : Aldo Henrique
// Descrição   : Lista 1 exercicio 2
// Autor(a)    : Joseiltom Dantas de Oliveira Junior       CPD: 042520
// Data atual  : 17/04/2018
Var
// Seção de Declarações das variáveis 
c : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("Informe a temperatura em C:")
leia(c)
escreval("Está temperatura é equivalente a ", ((9 * c + 160) / 5), "Fahrenheit")

Fimalgoritmo