Algoritmo "semnome"
// Disciplina  : LPOO
// Professor   : Aldo Henrique
// Descrição   : Lista 1 exercicio 5
// Autor(a)    : Joseiltom Dantas de Oliveira Junior       CPD: 042520
// Data atual  : 17/04/2018
Var
// Seção de Declarações das variáveis 
num : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreval("Informe um numero:")
leia(num)
escreval("O valor de ", num, " ao quadrado é", (num^2))

Fimalgoritmo