Algoritmo "semnome"
// Disciplina  :  [LPOO]
// Professor   : Aldo Henrique
// Descrição   : Lista 3 Exercicio 2
// Autor(a)    : Joseiltom Dantas de Oliveira Junior CPD: 042520
// Data atual  : 18/04/2018
Var
// Seção de Declarações das variáveis 
n, i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para n de 1 ate 10 faca
    para i de 1 ate 10 faca
        escreval(i, " *", n, " =", (n *i))
    fimpara
fimpara

Fimalgoritmo